[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
spicy = "https://spicy-rpc.chiliz.com/"
thirdweb = "https://88882.rpc.thirdweb.com/ddf001d0d15ae5cbc29b2b62c6591f35"
